spring:
  application:
    name: 4vidia-bookstore-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.116.64.14:13306/nhn_academy_13

    username: nhn_academy_13
    password: EOcV(baaATcu3lny

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true


        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 100

  elasticsearch:
    uris: s4.java21.net:9200
    username: elastic
    password: nhnacademy123!
    socket-timeout: 30s
    connection-timeout: 5s
