spring:
  application:
    name: 4vidia-bookstore-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://s4.java21.net:13306/project_be12_team4

    username: project_be12_team4
    password: Qrs8WavVsmxaQd[O

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true


        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 100
    #SMTP
  mail:
      host: smtp.gmail.com
      port: 587
      username: 4vidia.bookservice@gmail.com
      password: jnstvwwweeauxmzt
      properties:
        mail:
          smtp:
            starttls:
              enable: true
            auth: true



  elasticsearch:
    uris: s4.java21.net:9200
    username: elastic
    password: nhnacademy123!
    socket-timeout: 30s
    connection-timeout: 5s
  cloud:
    openfeign:
      client:
        config:
          ollama-client:
            connect-timeout: 5000
            read-timeout: 60000

          reranker-client:
            connect-timeout: 5000
            read-timeout: 30000

cloud:
  aws:
    s3:
      endpoint: http://storage.java21.net
      bucket: 4vidia
    credentials:
      access-key: gaNAQg19pCH82fuMbsU2
      secret-key: ${MINIO_SECRET_KEY}
    region:
      static: us-east-1
    stack:
      auto: false


image:
  default:
    thumbnail: http://storage.java21.net:8000/4vidia/default-book-cover.png


eureka:
  client:
    service-url:
      defaultZone: http://${ADMIN_ID}:${ADMIN_PASSWORD}@4vidia-discovery-1:8080/eureka/


toss:
  secretKey: test_sk_Gv6LjeKD8aYzQLpyoGzM8wYxAdXy




