spring:
  application:
    name: 4vidia-bookstore-service
  data:
    redis:
      cart:
        host: s4.java21.net
        port: 6379
        password: ${REDIS_PASSWORD}
        database: 384 # local 장바구니 아이템 저장용
        timeout: 5000ms
      dormant:
        host: s4.java21.net
        port: 6379
        password: ${REDIS_PASSWORD}
        database: 383
        timeout: 5000ms
      bestseller:
        host: s4.java21.net
        port: 6379
        password: ${REDIS_PASSWORD}
        database: 382 # 매 시간 저장(메인페이지에 띄울 베스트셀러)
        timeout: 5000ms
      ai:
        host: s4.java21.net
        port: 6379
        password: ${REDIS_PASSWORD}
        database: 388
        timeout: 5000ms
      signup:
        host: s4.java21.net
        port: 6379
        password: ${REDIS_PASSWORD}
        database: 381
        timeout: 5000ms
      isbn:
        host: s4.java21.net
        port: 6379
        password: ${REDIS_PASSWORD}
        database: 385
        timeout: 5000ms

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://s4.java21.net:13306/project_be12_team4?serverTimezone=Asia/Seoul&characterEncoding=UTF-8

    username: project_be12_team4
    password: ${MYSQL_PASSWORD}

    # DBCP
    type: org.apache.commons.dbcp2.BasicDataSource

    dbcp2:
      initial-size: 5
      max-total: 25
      max-idle: 10
      min-idle: 5
      test-on-borrow: true
      validation-query: SELECT 1
      max-wait: 3000ms

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true


        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 100
    #SMTP
  mail:
      host: smtp.gmail.com
      port: 587
      username: 4vidia.bookservice@gmail.com
      password: ${SMTP_PASSWORD}
      properties:
        mail:
          smtp:
            starttls:
              enable: true
            auth: true



  elasticsearch:
    uris: s4.java21.net:9200
    username: elastic
    password: ${NHN_PASSWORD}
    socket-timeout: 30s
    connection-timeout: 5s
  cloud:
    openfeign:
      client:
        config:
          ollama-client:
            connect-timeout: 5000
            read-timeout: 60000

          reranker-client:
            connect-timeout: 5000
            read-timeout: 30000

  rabbitmq:
    host: s4.java21.net
    port: 5672
    username: admin
    password: ${NHN_PASSWORD}
    virtual-host: /4vidia
    listener:
      simple:
        retry: # 재시도
          enabled: true
          max-attempts: 3
          initial-interval: 1000ms
          multiplier: 2.0 # 바로하면 실패할 확률 높으니 실패시 2배 시간 대기
          max-interval: 10000ms

cloud:
  aws:
    s3:
      endpoint: http://storage.java21.net:8000
      bucket: 4vidia
    credentials:
      access-key: gaNAQg19pCH82fuMbsU2
      secret-key: ${MINIO_SECRET_KEY}
    region:
      static: us-east-1
    stack:
      auto: false


image:
  default:
    thumbnail: http://storage.java21.net:8000/4vidia/default-book-cover.png



eureka:
  client:
    service-url:
      defaultZone: http://${ADMIN_ID}:${ADMIN_PASSWORD}@4vidia-discovery-1:8080/eureka/
    # 유레카 서버에서 서비스 목록을 새로고침하는 주기 (기본 30초 -> 5초)
    registry-fetch-interval-seconds: 5

  instance:
    # 1. 유레카 서버에 "나 살았어"라고 신호 보내는 주기 (기본 30초 -> 10초)
    lease-renewal-interval-in-seconds: 10
    # 2. 신호가 안 오면 죽은 걸로 간주하는 시간 (기본 9

google:
  api:
    api-keyList: ${GOOGLE_API_KEY}
    api-key2: ${GOOGLE_API_KEY2}
    model: gemini-2.5-flash

aladin:
  api:
    key: ${ALADIN_API_KEY1}

toss:
  secretKey: ${TOSS_SECRET_KEY}

server:
  port: 8080
  tomcat:
    threads:
      max: 200        # 동시에 처리 가능한 요청 Thread 수
      min-spare: 20   # 항상 대기 중인 최소 Thread
    accept-count: 100 # Thread 꽉 찼을 때 대기 큐

