spring:
  application:
    name: 4vidia-bookstore-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://s4.java21.net:13306/project_be12_team4

    username: project_be12_team4
    password: Qrs8WavVsmxaQd[O

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true


        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 100


  elasticsearch:
    uris: s4.java21.net:9200
    username: elastic
    password: nhnacademy123!
    socket-timeout: 30s
    connection-timeout: 5s



eureka:
  client:
    service-url:
      defaultZone: http://${ADMIN_ID}:${ADMIN_PASSWORD}@4vidia-discovery-1:8080/eureka/


toss:
  secretKey: test_sk_Gv6LjeKD8aYzQLpyoGzM8wYxAdXy