### 주소 등록
# 회원가입 먼저 해야함
POST http://localhost:8080/addresses
Content-Type: application/json
X-User-Id: 5

{
  "alias": "회사",
  "roadAddress": "동구 지산동",
  "zipCode": "11111",
  "addressDetail": "101호"
}

### 주소 등록2
# 회원가입 먼저 해야함
POST http://localhost:8080/addresses
Content-Type: application/json
X-User-Id: 5

{
  "alias": "집2",
  "roadAddress": "동구 동명동",
  "zipCode": "62237",
  "addressDetail": "105호"
}



### 주소 전체 조회 (사용자마다 여러개 있음)
GET http://localhost:8080/addresses
Content-Type: application/json
X-User-Id: 5

### 주소 수정
PUT http://localhost:8080/addresses/11
Content-Type: application/json
X-User-Id: 5

{
  "alias": "우리집",
  "roadAddress": "동구 광산구",
  "zipCode": "22222",
  "addressDetail": "301호"
}


### 주소 삭제
DELETE http://localhost:8080/addresses/12
Content-Type: application/json
X-User-Id: 5


### 기본 주소 변경
PUT http://localhost:8080/addresses/change-default/11
Content-Type: application/json
X-User-Id: 5

### 기본 주소 조회
GET http://localhost:8080/addresses/default
Content-Type: application/json
X-User-Id: 5

