### 주소 등록
POST http://localhost:8084/my/addresses
Content-Type: application/json
X-USER-ID: 5

{
  "alias": "회사",
  "roadAddress": "동구 지산동",
  "zipCode": "11111",
  "addressDetail": "101호"
}

### 주소 등록2
POST http://localhost:8084/my/addresses
Content-Type: application/json
X-USER-ID: 5

{
  "alias": "집2",
  "roadAddress": "동구 동명동",
  "zipCode": "62237",
  "addressDetail": "105호"
}

### 주소 전체 조회
GET http://localhost:8084/my/addresses
Content-Type: application/json
X-USER-ID: 5

### 주소 단일 조회
GET http://localhost:8084/my/addresses/11
Content-Type: application/json
X-USER-ID: 5

### 주소 수정
PUT http://localhost:8084/my/addresses/11
Content-Type: application/json
X-USER-ID: 5

{
  "alias": "우리집",
  "roadAddress": "동구 광산구",
  "zipCode": "22222",
  "addressDetail": "301호"
}

### 주소 삭제
DELETE http://localhost:8084/my/addresses/12
Content-Type: application/json
X-USER-ID: 5

### 기본 주소 변경
PUT http://localhost:8084/my/addresses/change-default/11
Content-Type: application/json
X-USER-ID: 5

### 기본 주소 조회
GET http://localhost:8084/my/addresses/default
Content-Type: application/json
X-USER-ID: 5






### 등급 조회
GET http://localhost:8084/my/grades
Content-Type: application/json
X-USER-ID: 5

### 등급 변경
PUT http://localhost:8084/my/grades/4
Content-Type: application/json
X-USER-ID: 5






### 회원가입
POST http://localhost:8084/my/signup
Content-Type: application/json

{
  "email": "회원1@test.com",
  "password": "회원1@naver.com",
  "name": "고길동",
  "phone": "01011112222",
  "birthDate": "2000-01-21"
}





### 이메일로 아이디 찾기
GET http://localhost:8084/my/users?email=jjang@naver.com
Content-Type: application/json



### 회원정보 조회 (마이페이지)
GET http://localhost:8084/my/profile
Content-Type: application/json
X-USER-ID: 5

### 회원정보 수정
PATCH http://localhost:8084/my/profile
Content-Type: application/json
X-USER-ID: 5

{
  "name": "홍길동 이름수정",
  "phone": "010-1111-2222"
}

### 회원 비밀번호 변경
PATCH http://localhost:8084/my/change-password
Content-Type: application/json
X-USER-ID: 5

{
  "currentPassword": "회원1@naver.com",
  "newPassword": "회원1@naver.com2",
  "confirmPassword": "회원1@naver.com2"
}

### 회원 탈퇴
PATCH http://localhost:8084/my/delete
Content-Type: application/json
X-USER-ID: 6

{
  "currentPassword": "회원1@naver.com2"
}



### 좋아요 조회
GET localhost:8084/my/likes
X-User-Id: 7

### 좋아요 등록
POST localhost:8084/my/likes/1
X-User-Id: 7

### 좋아요 삭제
DELETE localhost:8084/my/likes/1
X-User-Id: 7