
### 포인트 적립 - 주문완료
POST http://localhost:8080/points/reward
Content-Type: application/json
X-USER-ID: 5

{

  "orderId": 2002,
  "amount": 1500
}



### 포인트 사용
POST http://localhost:8080/points/use
Content-Type: application/json
X-USER-ID: 5

{
  "orderId": 2001,
  "amount": 500


}


### 포인트 환불

POST http://localhost:8080/points/refund
Content-Type: application/json
X-USER-ID: 5

{
  "orderId": 2001,
  "amount": 500

}


### 정책에 따른 포인트 적립

POST http://localhost:8080/points/policy-reward
Content-Type: application/json
X-USER-ID: 5

{
  "orderId": 2001,
  "policyId": 3,
  "amount": 2000
}

### 보유 포인트 조회
GET http://localhost:8080/points/remain
X-USER-ID: 5


### 환불 테스트
POST http://localhost:8080/points/refund
X-USER-ID: 5
Content-Type: application/json

{
  "orderId":2001,
  "amount":500
}

### 포인트 만료 테스트
GET http://localhost:8080/points/expire-soon
X-USER-ID: 5

### 포인트 전체 내역 조회
GET http://localhost:8080/points/history
X-USER-ID: 5
